### PR TITLE
Adapt function naming from kerberos

### PR DESCRIPTION
**Pull request by c-mertes**
krb5_rc_resolve_full -> k5_rc_resolve
krb5_rc_close -> k5_rc_close

### CODE REVIEW

**Comment by c-mertes** [comment]
this could fix #46 and fix #52

**Comment by trenta** [comment]
Can we have this patch merged with a new release please.

Cheers

Trent

**Comment by rezib** [comment]
Thank you so much @c-mertes you made my day :)

@hautreux, is there any chance you merge it in some way?

**Comment by hautreux** [comment]
started to work on removing replay cache disabling support in auks.
no longer necessary if not longer supported by the libkrb5 API.
this will remove the undefined symbols when compiling against libkrb5 >= 1.18

**Comment by hautreux** [comment]
fixed in commit b84ae7334400bf1c5dd458bdc530b2939bbd4cdc.

**Pull request closed without merging**
